openapi: 3.0.0
info:
  title: Flood Forecast API
  description:
    This API provides flood forecast data happening in Thailand.
    * Rain and flood warning gathered by google form.
    * Weather report every 3 hours by OpenWeatherAPI.
    * Flood forecast data by WCPC.
    * Dam water level by egat_dam.
  version: 3.0.0
servers:
  - url: /flood-forecast-api
paths:
  /weather-report:
    get:
      summary: Returns a list of flood forecast data happening in Thailand.
      tags:
        - weatherreport
      operationId: controller.get_weather_report
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherReport'
  /weather-report/{sector}:
    parameters:
    - name: sector
      in: path
      required: true
      description: sector name
      schema:
        type: string
    get:
      summary: Returns complete details of the specified sector weather report
      tags: 
        - weatherreport
      operationId: controller.get_weather_report_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherReport'
          links:
            humidRainSector:
              operationId: controller.get_humidity_and_rain_freq
              parameters:
                sector: $response.body#/sector
  /weather-report/{sector}/humidrain:
    parameters:
    - name: sector
      in: path
      required: true
      description: sector name
      schema:
        type: string
    get:
      summary: Returns complete details of the specified sector humidity and rain
      tags: 
        - weatherreport
      operationId: controller.get_humidity_and_rain_freq
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HumidityRainFreq'
  /weather-report/{sector}/avg:
    parameters:
    - name: sector
      in: path
      required: true
      description: sector name
      schema:
        type: string
    get:
      summary: Returns complete details of the sector humidity avg
      tags: 
        - weatherreport
      operationId: controller.get_owr_avg_humidity
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwrHumidity'
  /damlevel:
    get:
      summary: Returns a list of dam water level in sector of Thailand.
      tags:
        - damlevel
      operationId: controller.get_dam_level
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DamLevel'
  /damlevel/{sector}:
    parameters:
    - name: sector
      in: path
      required: true
      description: sector name
      schema:
        type: string
    get:
      summary: Returns complete details of the specified sector
      tags: 
        - damlevel
      operationId: controller.get_dam_level_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DamLevel'
          links:
            damLevelSector:
              operationId: controller.get_dam_level_date_reten
              parameters:
                sector: $response.body#/sector
  /damlevel/{sector}/water:
    parameters:
    - name: sector
      in: path
      required: true
      description: sector detail of the dam water
      schema:
        type: string
    get:
      summary: Returns complete details of the specified dam water
      tags: 
        - damlevel
      operationId: controller.get_dam_level_date_reten
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DamLevelWater'
  /forecast:
    get:
      summary: Returns a list of flood forecast of Thailand.
      tags:
        - forecast
      operationId: controller.get_forecast
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Forecast'
  /forecast/{province}:
    parameters:
    - name: province
      in: path
      required: true
      description: province detail of the flood forecast
      schema:
        type: string
    get:
      summary: Returns complete details of the specified province flood forecast
      tags: 
        - forecast
      operationId: controller.get_forecast_details_province
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forecast'
  /forecast/{province}/crossdam:
    parameters:
    - name: province
      in: path
      required: true
      description: province detail of the flood forecast and dam water level
      schema:
        type: string
    get:
      summary: Returns complete details of the specified province flood.
      tags: 
        - forecast
      operationId: controller.get_forecast_damlevel
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastDamLevel'
  /questionnaire:
    get:
      summary: Returns a list of flood questionnaire that we collected.
      tags:
        - questionnaire
      operationId: controller.get_questionnaire
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Questionnaire'
  /questionnaire/{province}:
    parameters:
    - name: province
      in: path
      required: true
      description: detail of questionnaire by province
      schema:
        type: string
    get:
      summary: Returns complete details of the specified flood type
      tags: 
        - questionnaire
      operationId: controller.get_questionnaire_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Questionnaire'
  /questionnaire/{province}/crossdam:
    parameters:
    - name: province
      in: path
      required: true
      description: province detail of the questionnaire and dam water level
      schema:
        type: string
    get:
      summary: Returns complete details of the specified province flood.
      tags: 
        - questionnaire
      operationId: controller.get_rain_freq_and_damlevel
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RainFreqLevel'
  /questionnaire/{sector}/avg:
    parameters:
    - name: sector
      in: path
      required: true
      description: detail of avg rain frequency from questionnaire
      schema:
        type: string
    get:
      summary: Returns complete details avg rain frequency from questionnaire.
      tags: 
        - questionnaire
      operationId: controller.get_qestion_avg_rain_freq
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionRainFreq'
  

components:
  schemas:
    WeatherReport:
      type: object
      properties:
        sector:
          type: string
        main:
          type: string
        humidity:
          type: integer
        description:
          type: string
        ts:
          type: string
        province:
          type: string
    DamLevel:
      type: object
      properties:
        date:
          type: string
        sector:
          type: string
        water_retention:
          type: integer
        can_reveive_more:
          type: integer
    DamLevelWater:
      type: object
      properties:
        date:
          type: string
        water_retention:
          type: integer
    Forecast:
      type: object
      properties:
        month:
          type: string
        TAMBON_T:
          type: string
        AMPHOE_T:
          type: string
        PROV_T:
          type: string
        Type:
          type: string
        sector:
          type: string
    Questionnaire:
      type: object
      properties:
        sector:
          type: string
        province:
          type: string
        amphoe:
          type: string
        warning_freq:
          type: string
        warning_way:
          type: string
        want_warning_way:
          type: string
        type:
          type: string
        flood_freq:
          type: string
        rain_freq:
          type: integer
    RainFreqLevel:
      type: object
      properties:
        sector:
          type: string
        province:
          type: string
        rain_freq:
          type: integer
        can_receive_more:
          type: integer
        water_retention:
          type: integer
    ForecastDamLevel:
      type: object
      properties:
        sector:
          type: string
        province:
          type: string
        type:
          type: string
        can_receive_more:
          type: integer
        water_retention:
          type: integer
        date:
          type: string
    ReportForecast:
      type: object
      properties:
        sector:
          type: string
        humidity:
          type: integer
        main:
          type: string
        description:
          type: string
        ts:
          type: string
        Type:
          type: string
        month:
          type: string
    QuestionRainFreq:
      type: object
      properties:
        sector:
          type: string
        avg_rain_freq:
          type: integer
    OwrHumidity:
      type: object
      properties:
        sector:
          type: string
        avg_humidity:
          type: integer
    HumidityRainFreq:
      type: object
      properties:
        sector:
          type: string
        humidity:
          type: integer
        rain_freq:
          type: integer
        province:
          type: string
        